CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE "room" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" VARCHAR(255) NOT NULL,
  "gameType" VARCHAR(255) NOT NULL,
  "maxPlayers" INTEGER NOT NULL DEFAULT 2,
  "isStarted" BOOLEAN NOT NULL DEFAULT FALSE
);

